name: learning-github
run-name: learning github actions for first time

on:
  push:
   branches:
    - master
    
jobs:
   firstjob:  
      runs-on: windows-2019
      steps: 
   
      - name: checkout-my-code
        uses: actions/checkout@v3.3.0
      
      - name: add msbuild path
        uses: microsoft/setup-msbuild@v1.1
      
      - name: restore my nuget package from solution
        run: nuget restore WebApplication/WebApplication.sln
      
      - name: build my code using msbuild
        run: msbuild WebApplication/WebApplication.sln /p:Configuration=Release /p:DeployTarget=Package /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeployOnBuild=true
        
      - name: upload my build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: buildartifact
          path: '**/obj/Release/Package/**'
     
